apiVersion: apps/v1
kind: Deployment
metadata:
   name: mywp
spec:
   replicas: 1
   selector:
      matchLabels:
         env: frontend
   template:
      metadata:
         name: "mywp"
         labels: 
           env: frontend
      spec:
         containers:
          - name: mywp
            image: wordpress:5.1.1-php7.3-apache




